### ISSUE TITLE
Add support for sentinel

### ISSUE THREAD

**Issue by m-yosefpor** [OT-CONTAINER-KIT/redis-operator#122]
Feature request: Adding support for sentinel service which enhances redis clustering experience.

**Comment by iamabhishek-dubey** [comment]
Hey @m-yosefpor,

Thanks for opening up this issue but since we are using the Redis cluster mechanism, so the failover of master and slave is already being managed by Redis itself. This feature would have been very helpful if we have 1 master and 1 slave setup but in cluster mode, Redis itself is managing the failover.
