### ISSUE TITLE
No Persistence needed

### ISSUE THREAD

**Issue by mohammad-babaei** [OT-CONTAINER-KIT/redis-operator#140]
What should i do if i do not need the PVC and don't want the snapshoting feature.

**Comment by iamabhishek-dubey** [comment]
You can remove the storage block and it will not have any storage attached and rdb snapshotting will also be disabled. Also, I am closing this issue because it's not a feature or issue request.

**Comment by plachta11b** [comment]
I have tried to disable persistance by removing spec.storage from RedisCluster but i have got `Can't open /data/nodes.conf in order to acquire a lock: Permission denied` on version 0.8.0. I would prefer ability to set `spec.kubernetesConfig.env.PERSISTENCE_ENABLED` to "false" and directly turn off any backups. My cluster does not survive scenario when all pods are deleted due to IP reconfiguration so even nodes.conf persistence is useless to me (just for now before upgrade i hope).

**Comment by batistein** [comment]
@plachta11b How did you fix that?
